version: '1.0'
name: main-pip
displayName: main-pip
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: stage-build
    displayName: 构建与发布部署
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build-nodejs
        displayName: Nodejs 构建
        nodeVersion: 25.4.0
        commands:
          - '# 设置NPM源,提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 执行编译命令(使用npm ci保证依赖一致性)'
          - npm install
          - npm run docs:build
          - '# 检查构建结果目录'
          - ls -la docs/.vitepress/dist/
          - '# 打包产物为 output.tar.gz'
          - tar -czf output.tar.gz -C docs/.vitepress/dist .
          - '# 验证打包结果'
          - ls -la output.tar.gz
          - tar -tzf output.tar.gz
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - output.tar.gz
        caches: []
        strategy: {}
      - step: publish@general_artifacts
        name: publish-artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build-nodejs
      - step: publish@release_artifacts
        name: publish-release
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        strategy: {}
        dependsOn: publish-artifacts
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: ali2026
          hostID:
            - ddcb52f3-610e-4d38-bef6-54427fe27014
        deployArtifact:
          - source: artifact
            name: output
            target: /opt/wwwroot
            artifactRepository: release
            artifactName: output
            artifactVersion: latest
        script:
          - cd /opt/wwwroot
          - ls -la
          - tar -zxf output.tar.gz
          - rm -f output.tar.gz
          - chmod -R 755 .
          - echo Deploy Success
        notify: []
        strategy:
          retry: '0'
        dependsOn: publish-release
